### ISSUE TITLE
CSS-Scaling influences

### ISSUE THREAD

**Issue by Contract47** [robicch/jQueryGantt#102]
When applying CSS scaling (e.g. **transform: scale(.5)** ) on the chart's parent container, the mouse interactions and some displayed components are off, e.g. 

- bars are positioned outside of their corresponding rows (when scaled before loading the chart)
- offset when
  - dragging the bars themselves
  - their dependencies or 
  - their start- and endpoints

I didn't find any clues towards that matter, that's why I wanted to contact you outside of github first, in case I just missed something that's already implemented.

**Comment by robicch** [comment]
css scaling could affects on mouse events
