### ISSUE TITLE
Mouse wheel scroll does not work on IE version < =11 on firstBox

### ISSUE THREAD

**Issue by itszerocode** [robicch/jQueryGantt#104]
On IE <=11, when you try scrolling using mouse wheel, the scrolling does not work. This is observed on 
firstBox.on('mousewheel MozMousePixelScroll', function (event) method,

           ` var deltaY = event.originalEvent.wheelDeltaY;
`
here the **wheelDeltaY** property is undefined.. 

Probable fix is to use fall back code as 

```
var deltaY = event.originalEvent.wheelDeltaY;
            if (!deltaY)
                deltaY = event.originalEvent.wheelDelta;
```

**Comment by robicch** [comment]
Patch applyed
