### ISSUE TITLE
Bug scroll table activities

### ISSUE THREAD

**Issue by eduardobelchior** [robicch/jQueryGantt#106]
When using it with the PHP framework Laravel and even using the pre-established values ​​it has a bug when scrolling the activity table, as shown in the image below.

![capturar](https://user-images.githubusercontent.com/18681450/30527804-ec55bd78-9c02-11e7-8ad1-1f8815183e71.PNG)

**Comment by robicch** [comment]
I dont' know PHP neither Laravel.
At glance it seems an error related with css or something similar, not PHP.
Cheers,

roberto

**Comment by rafalpospiech** [comment]
try css from https://github.com/robicch/jQueryGantt/issues/108
