### ISSUE TITLE
Resource Editor closes unexpectedly, when hitting del Button

### ISSUE THREAD

**Issue by ilovefooty** [robicch/jQueryGantt#113]
Hi,

actually this issue is also true for your gantt project online demo. I can open the ressource editor and add resources but when I want to delete one - the editor closes immediately and there is no way of actually saving that change - could you please have a look at this?

I tried IE, Chrome and Firefox (no difference)

**Comment by whyblade** [comment]
Hi,

the reason is the background div. It thinks it is clicked and closes the dialog.
Hotfix:
comment the following lines in dialog.js out:
```
//	bg.on("click",function(event){
//		if ($(event.target).closest(".bwinPopupd").length <= 0)
//			bg.trigger("close");
//	});
```

**Comment by robicch** [comment]
fixed on just released version
