### ISSUE TITLE
NPM installation support

### ISSUE THREAD

**Issue by ajesicus** [robicch/jQueryGantt#115]
Hi there,

Is it possible to add a support for NPM installation?

**Comment by robicch** [comment]
I don't know NPM and have no time right now to have a look to, but you can contribute if you want.

**Comment by marclaporte** [comment]
I suggest to re-open the issue. I can ask a colleague to prepare a PR with the necessary files.

**Comment by marclaporte** [comment]
Some unofficial sources:

- https://www.npmjs.com/package/jquery-gantt-editor
- https://www.npmjs.com/package/jq-gantt
