### ISSUE TITLE
Dependency with calculation

### ISSUE THREAD

**Issue by micahhlc** [robicch/jQueryGantt#116]
Dear Robicch, again thanks for the nice plugin. btw, anyway i can buy a support service from your team? 

My question is, on the dependency, i would like to have 20-2d, means, this task can start 2days earlier after task 20 has finished. 
Another example, 20+3d, it means, this task can start 3 days later after the task 20 has finished.

**Comment by robicch** [comment]
You can, just write 20:3 or 20:-3
