### ISSUE TITLE
Summary Task dates calculations are probably incorrect.

### ISSUE THREAD

**Issue by itszerocode** [robicch/jQueryGantt#119]
As per commonly known project server rules,
**Start date.** A summary task gets its start date from the earliest start date among its subtasks.
**Finish date.** The finish date for a summary task is the latest finish date among the subtasks.

but as per the logic implemented here, if the Summary Task date is already lesser than any of its subtasks, it does not changes the date of summary task to follow the above mentioned rule. Same for the summary tasks end calculations. 

We might need to update the logic in GanttTask.js -> UpdateTree function to implement these rules.

**Comment by robicch** [comment]
Hi,
this is not really an issue, but the desired behavior.
On our model parent tasks are not merely a "group", but have its own state, dates, costs, assignments.
Twproject, the product that lead this component development, encourage the delegation of responsibility, and this can be done only giving "parents" this behavior.
