### ISSUE TITLE
Task Dates not updating properly with dependencies.

### ISSUE THREAD

**Issue by joescarpetta** [robicch/jQueryGantt#121]
In attached image on row 13: Complete Session Materials. Start Date is 2/1/2018, expectation was that it would show the minimum date from within it's grouping, in this case 2/17/2018.

Row 14 has a dependency on Row 8, removing the dependency does not correct the date. The Duration does not update either.

<img width="1654" alt="gantt" src="https://user-images.githubusercontent.com/36014844/35649226-6498ec0c-06a6-11e8-802e-0c39ae7cabe0.png">

**Comment by robicch** [comment]
Hi Joe,
this is not really an issue, but the desired behavior.
On our model parent tasks are not merely a "group", but have its own state, dates, costs, assignments.
Twproject, the product that lead this component development, encourage the delegation of responsibility, and this can be done only giving "parents" this behavior.
