### ISSUE TITLE
[Feature request] Export diagram 

### ISSUE THREAD

**Issue by Azef1** [robicch/jQueryGantt#131]
Hi,

It will be nice to add a function to export the diagram in png or svg or pdf. It will be useful to print the diagram.

Is it possible to add this function ?

Thx

**Comment by robicch** [comment]
PNG or SVG export doesn't work fine for very large projects.
We have just developed the pdf export for the PRO version that will be released with Twproject 6.4.64001
Contact me directly (rbicchierai a t open-lab dot com) if you need more info about PRO version.
