### ISSUE TITLE
bootstrap

### ISSUE THREAD

**Issue by oscarsantook** [robicch/jQueryGantt#132]
It might not be compatible with bootstrap? The screens are not displayed correctly. Please confirm. The problem found when used tabs.

**Comment by nicoyarce** [comment]
I have the same issue by using Bootstrap 4, the problem in my case is that the rows are not aligned

**Comment by robicch** [comment]
We do not use bootstrap, and the html code of this components is really sensible to css.
I cannot guarantee it works with bootstrap or others frameworks
