### ISSUE TITLE
Clear Project

### ISSUE THREAD

**Issue by oscarsantook** [robicch/jQueryGantt#133]
When click on "Clear Project" button, then, can not add tasks any more. Maybe var canAdd is not set as true.

**Comment by virajkanwade** [comment]
`ge.saveProject` misses `"canAdd": true,` in the json saved.

**Comment by virajkanwade** [comment]
Probably in
`
GanttMaster.prototype.saveGantt = function (forTransaction) {
`

along with
`ret.canWrite = this.permissions.canWrite;`
`ret.canWriteOnParent = this.permissions.canWriteOnParent;`

also add 
`
    ret.canAdd = this.permissions.canAdd;
`

**Comment by robicch** [comment]
Fixed, thanks
