### ISSUE TITLE
Gantt freezes when moving a child task outside its parent's time span

### ISSUE THREAD

**Issue by jugolm** [robicch/jQueryGantt#135]
This happens more often when a task has a single child, although I've seen it sometimes with multiple children. Sometimes I'd move it once and nothing happens, then I'd move it again and then it freezes.

It throws a "too much recursion" error that loops between the functions _updateTree_, _Task.prototype.moveTo_ and _Task.prototype.setPeriod_

**Comment by taochunyu** [comment]
delete this line https://github.com/robicch/jQueryGantt/blob/5ae79327423cf29102a0cf71c6d3bbcb8dc16b6b/ganttTask.js#L141

**Comment by robicch** [comment]
Unable to reproduce. Please attach an example
