### ISSUE TITLE
Printing gantt-diagram

### ISSUE THREAD

**Issue by NamanSuri** [robicch/jQueryGantt#137]
Hi Robicch,

Has the issue of printing all the Gantt (.splibox2) items for long projects i.e. having more than 300 task been resolved on the open source version.
Also the Print to PDF/Export functionality only available in Commercial version and not on the open source version.

As we are facing issues and we are able to print all the 300 tasks but the Gantt is only printing items visible on the screen.

Thanks in advance.

Naman

**Comment by robicch** [comment]
A single SVG object larger than a page is not printed on most browser. After weeks wasted on this we have implemented a PDF print. Currently available in the PRO version only.
