### ISSUE TITLE
Discrepancy in Start Date and End Date

### ISSUE THREAD

**Issue by pratiksaha37** [robicch/jQueryGantt#140]
I am facing issues while implementing Ganttchart.js to my project. We are not considering Saturday and Sundays as holidays so I have changed isHoliday function under i18n.js file. But still, there is some discrepancy of one day with the actual start date/ end date of the project(Not for every task though). It would be really helpful if you tell me what are the changes need to be performed to solve that.

Best Regards,
Pratik Saha

**Comment by robicch** [comment]
Did you check that start, end and duration defined on json matches?
