### ISSUE TITLE
Change duration of task

### ISSUE THREAD

**Issue by hailehong** [robicch/jQueryGantt#144]
Hi @robicch,
Thank you for your wonderful code. I run the gantt.html file. When I change the duration of task '**gantt part**' from 2 to 15, the demo show contraint error. But if I change the duration step by step 2 to 3, 3 to 4,..,14 to 15, it is OK (time of other tasks are changed).
Could you show me the reason for this?

**Comment by robicch** [comment]
There is no reason, but probably a bug :-)

**Comment by hailehong** [comment]
Hi @robicch,
I really need to edit the duration during reschedule a project.
Changing the duration step by step is OK, Could you give me a clue, how can i do changing duration step by step in the source code?
Thank you very much!

**Comment by robicch** [comment]
I'm unable to replicate the issue on gantt.twproject.com. Could you please attache an example?
