### ISSUE TITLE
Today date line is not correctly displaying

### ISSUE THREAD

**Issue by dhirusarania** [robicch/jQueryGantt#146]
1. Today date line is a little off on some cases. below is a screenshot taking on 15 February at 8:12am but the date line shows 16 February. What i found is if I use the actualize data code on the sample then it is showing fine. but we cannot use that.

![whatsapp image 2019-02-15 at 8 13 09 am](https://user-images.githubusercontent.com/33983632/52831170-fcb0d680-3116-11e9-8754-7e2bee61b182.jpeg)

2. You can see on the screenshot below the event is starting on the middle of the day instead of the start. How can this be fixed?

![capture](https://user-images.githubusercontent.com/33983632/52831339-a2644580-3117-11e9-9c0f-95d8fd85e696.PNG)

**Comment by kapilrajnale** [comment]
for second issue , try to set start and end date time like below code in ganttDrawerSVG.js i.e. in Ganttalendar.prototype.create. 
 
            start.setHours(0, 0, 0, 0);
            end.setHours(23, 59, 59, 999);
