### ISSUE TITLE
What is used as elements of a Gantt chart?

### ISSUE THREAD

**Issue by it19862** [robicch/jQueryGantt#151]
1. If I understood correctly, then the “table” is used as the element “Element_1” (see the picture).
Question.
1.1 What is used as an element of "Element_1" (see picture)?
1.2 Where in the code is the initialization of the element "Element_1"?
1.3 Where in the code can I change the format of the Element_1 element?

2. I could not understand what is used as an element of "Element_2" (see the picture).
Question.
2.1 What is used as an element of "Element_2" (see the picture)?
2.2 Where in the code is the element "Element_2" initialized?
2.3 Where in the code can I change the format of the Element_2 element?

3. I could not find in the project which element is used to display the tasks on the Gantt chart.
Question.
3.1 What is used as an element for displaying tasks on a Gantt chart?
3.2 Where in the code does the element initialize to display tasks?
3.3 Where in the code can I change the format of the element to display tasks?

![2019-07-28_14-22-20](https://user-images.githubusercontent.com/18245828/62009993-dbe0b880-b16d-11e9-840d-6b7f61997c2e.png)

**Comment by robicch** [comment]
The concept of the component is:
GanttMaster is the main controller. It contains "editor" and "gantt".
"editor" is an instance of GanttGridEditor (manages  the grid, left side part). editor.element is the jQuery proxy of Element_1. The grid composition is managed by templates, in particular "TASKROW".

"gantt" is an instance of Ganttalendar. gantt.element is the is the jquery element containing gantt. The gantt graph is a svg object referred by gantt.svg. 

Both are inited in the GantMaster.init.

The Task object contains the reference to rowElement (table) and ganttElement (gantt). 
Task grid part is managed by template "TASKROW" the gantt part is managed by code Ganttalendar.prototype.drawTask.

Hoping this helps.
Best regards,
Roberto
