### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by jpuchinger** [robicch/jQueryGantt#152]
Is there a way to have it so that when assigning dependencies the child isn't shuffled to the end of the host dependency. This way (in a manufacturing environment) you can have "units" that have a duration of 10 days, but start days staggered by say 2 days. 

Simply looking to have a related tree that if 1 item is adjusted they all adjust, however can occur simultaneously?

**Comment by robicch** [comment]
You can use a dependency with a negative lag e.g. "2:-1"
