### ISSUE TITLE
Is there a way to update the percentage done on the group item

### ISSUE THREAD

**Issue by stlpedro** [robicch/jQueryGantt#160]
First, thank you for making this amazing software available.  

The only problem that I encountered so far is that when I update a child item, the parent is not updated in the percentage.

For example:

Group 1
 - Task 1
 - Task 2 (100%)
 - Task 3

When I update Task 3 to 100% done, I expected Group 1 to be set to 33%.

Is that supported?

**Comment by robicch** [comment]
Not by the editor. 
You solution seems a little bit simplistic: who decided that the three task had the same relevance.
Moreover consider that in our approach "group 1" is not a "group" and could be wider that t1+t2+t3, son it could be hard to upgrade automatically the percentage.
