### ISSUE TITLE
Failed to read the 'localStorage' property from 'Window' 

### ISSUE THREAD

**Issue by dongtc** [robicch/jQueryGantt#161]
If chrome settting "Block third-party cookies" is checked and the ganttpage load in iframe, the error will happen.
![image](https://user-images.githubusercontent.com/13464443/79954684-3fef9d80-84b0-11ea-90b4-db17440b907d.png)

Can the code be compatible?

https://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failed-to-read-localstorage-from-window-access-deni

**Comment by robicch** [comment]
If you try it from local file system "file://" it could happen. Use a Apache or something elde.
