### ISSUE TITLE
Just something I noticed.

### ISSUE THREAD

**Issue by pokecheater** [robicch/jQueryGantt#164]
Hello TW-Gantt-Team.

First I want to thank you for this great open source project. Currently we are trying to use it inside an angular application. So in order to make it work I had to do a lot of customizations and there was something I noticed. 

Inside the gantt.html file you define the GantMaster Object with the name _ge_. And ocassionally this global variable is re used inside the GantMaster object inside the prototype functions:  _manageSaveRequired_ and _checkChanges_. Because in angularJS it is not so easy to use global variables I had to customize these two functions. And here its getting confusing to me because why the _Gant.html_ and the _gantMaster.js_ are seperate files but both are using the same global variable? From my understanding a separate file or class should be a closed standalone thing. 

So I just removed the _ge_ references inside _ganttMaster.js_ and replaced it with _this_ and then I have bind at the line  _this.element.on("saveRequired.gantt", this.manageSaveRequired.bind(this));_
the GantMaster object itself, so I have access to it inside the callback event function and then there is no need to use the global ge variable.

**Comment by robicch** [comment]
Hi,
thank you for pointing out this.
It is of course a nasty coding example :-), probably caused by an happy refactoring.
I'll fix and update the code asap

**Comment by pokecheater** [comment]
Yeah, this is one of these things that might get wrong during refactoring :). Thx for fixing.
