### ISSUE TITLE
Allow keyboard shortcuts

### ISSUE THREAD

**Issue by brentfraser** [robicch/jQueryGantt#165]
I like just entering the all the task names in a project first.  So to allow using the Enter key, add something like:

```
$(window).keypress(function(e){
  var code = e.which || e.keyCode;
  switch ( code )
  {
    case 13:  // return
      $('#workSpace').trigger('addBelowCurrentTask.gantt')
      return false;
    default:
      break;
  }
});```

**Comment by robicch** [comment]
There are already several keyboard shortcut.
have a look at ganttMaster and ganttGridEditor
