### ISSUE TITLE
Read-only Gantt

### ISSUE THREAD

**Issue by ATOPBIO** [robicch/jQueryGantt#175]
Hello,

I am trying to use it just to display tasks (loaded from my own database), what is the minimalistic approach to build the gantt to be read-only?

**Comment by ATOPBIO** [comment]
I would assume there would be no need to load all the scripts at the start, also perhaps no need to load jquery?

**Comment by robicch** [comment]
No. jQuery is mandatory

**Comment by robicch** [comment]
The minimum effort is to set ganmttmaster.permissions.canRwite=false
