### ISSUE TITLE
SVG Drawing is way off

### ISSUE THREAD

**Issue by gtjhin** [robicch/jQueryGantt#184]
Scrolling up and down make svg bar off by a lot.

![Screenshot 2021-07-02 172450](https://user-images.githubusercontent.com/86506471/124260965-787e1300-db5a-11eb-969e-411688a43de0.png)

**Comment by gtjhin** [comment]
var dimensions = {
			x     : Math.round((task.start - self.startMillis) * self.fx),
			y     : task.rowElement.position().top + self.taskVertOffset,
                        //    before: task.rowElement.position().top + task.rowElement.offsetParent().scrollTop() + self.taskVertOffset,
			width : Math.max(Math.round((task.end - task.start) * self.fx), 1),
			height: (self.master.showBaselines ? self.taskHeight / 1.3 : self.taskHeight)
		};

The  task.rowElement.offsetParent().scrollTop() inside _createTaskSVG()  cause the dimension calculation to be off, removing it fix the problem.

**Comment by robicch** [comment]
yes this is the right fix for jquery 3

**Comment by ypresta** [comment]
Hello,
I have used the plugin js Robbicch gantt
However, I have (565) lines as tasks. (lines taken from a database table .
 As a consequence, the page plugin get frozen which means there is no way to edit add only get to display. Chrome also gets frozen. any information????

**Comment by ypresta** [comment]
In opening chrome for robicch jquery gantt I had this Code d'erreur : SBOX_FATAL_MEMORY_EXCEEDED
