### ISSUE TITLE
Baseline Planned vs. Actual Timeline ?

### ISSUE THREAD

**Issue by nbao** [robicch/jQueryGantt#194]
Hi,
Is there a way to create a project baseline? I just want to compare the planned date and the actual date? Planned timeline below actual date and it cannot be moved!

Thanks

**Comment by robicch** [comment]
Have a look to function initializeHistoryManagement
It activate the view of task dates changes.
![image](https://user-images.githubusercontent.com/1381751/211510395-9e7d7ba1-3454-42dc-a35e-71fe8edf0cd8.png)

If you have a single history point it will represents your baseline.

**Comment by robicch** [comment]
With an informative tooltip :
![image](https://user-images.githubusercontent.com/1381751/211510740-95e3f9e4-304d-4e66-be84-86d791ea92b8.png)

**Comment by nbao** [comment]
I think it will be clear if we have more 2 fields planned start and end dates in the field, just add 1 extra line below.
