### ISSUE TITLE
gimmeBack.jsp Not Included

### ISSUE THREAD

**Issue by client4** [robicch/jQueryGantt#28]
The Export button linkes to gimmeBack.jsp, however gimmeBack.jsp is not included in the Github repository.  I'm not sure if this is intentional or not, but it does make the export button not useful.

**Comment by Edisson** [comment]
Hi! I'm new in web (js) programming. 
I embed your wonderful component in our Web (C#) project but can't understand how does the export have to work? please could you give me an advice?

**Comment by robicch** [comment]
Hi,
when you export something you want to save a file. 
As far as I know, there is no way to do this from js, but you need to get the file from the server using a special header.

Here is the .jsp code of gimmeBack.jsp:

<%@ page import="net.sf.json.JSONArray, net.sf.json.JSONObject" %>
<%
  String data = request.getParameter("prj");
  JSONObject o=JSONObject.fromObject(data);
  String filename = "project";
  //use the name of the first task to set the name of the file
  JSONArray tasks = o.getJSONArray("tasks");
  JSONObject task = tasks.getJSONObject(0);
  filename = task.getString("name");

  response.resetBuffer();
  response.setContentType("application/json");
  String filenameEncoded = filename + ".json";
  response.setHeader("content-disposition", "attachment; filename=" + filenameEncoded); //StringUtilities.normalize(rfs.getName())
  out.print(data);
%>
