### ISSUE TITLE
Task end date are not getting updated as per subtask

### ISSUE THREAD

**Issue by nidhisarvaiya** [robicch/jQueryGantt#29]
Hello,

Thanks for such a good component.

We are trying to use it on one of our application and facing issue with one of the scenario.

When a sub task calendar days are increased then, the calendar days of main task increases automatically. But when the same sub task days are reduced the days of main task are not reducing automatically - it reduces only when we manually drag the gantt bar of main task.

Can you please help us and let us know if we are missing anything in implementation.

Thanks for the help in advance.

Regards,
Nidhi Sarvaiya

**Comment by robicch** [comment]
Hi Nidhi,



> When a sub task calendar days are increased then, the calendar days of
> main task increases automatically. But when the same sub task days are
> reduced the days of main task are not reducing automatically - it reduces
> only when we manually drag the gantt bar of main task.
>
> Can you please help us and let us know if we are missing anything in
> implementation.
>
> This is the standard behavior in our model; parent task can be wider of
their children.

Cheers,

Roberto


-- 


  *Ing. Roberto Bicchierai - *Development Team Director
rbicchierai@open-lab.com   blog: roberto.open-lab.com

*open lab s.r.l.*
via venezia 18b 50121 firenze italia
Tel: +39 055 5522779

 See:

Twproject <http://twproject.com/>   *open-lab.com <http://open-lab.com>*

**Comment by nidhisarvaiya** [comment]
Thanks Roberto for quick reply.

Can you please guide us on event which we need to refer to customize for our requirement to update parent task date automatically on updating children.

Thanks,
Nidhi Sarvaiya
