### ISSUE TITLE
Jquery Conflicts

### ISSUE THREAD

**Issue by Tanmaydeveloper** [robicch/jQueryGantt#31]
Hi I am Thankful to the team to create such a great  tool but in my project I am using Jquery-1.11.2.js
which is creating conflicts in datefield of Gannt  Please tell how to get rid of this issue

**Comment by robicch** [comment]
Migration from jQuery 1.8 to 2.x is in progress, will be available middle march

**Comment by Tanmaydeveloper** [comment]
Hi Robicch ,
I tried to create some new thing in gannt,

I tried to add 2 more date columns in gannt , some minor changes I have done in js and the dates are coming fine but when I try to updates the dates via calendar it roll back to previous dates 

Can u tell me the steps to add extra date columns in Gannt Chart
