### ISSUE TITLE
Need to add extra date columns

### ISSUE THREAD

**Issue by Tanmaydeveloper** [robicch/jQueryGantt#34]
Hi Robicch ,
 I tried to create some new thing in gannt,

I tried to add 2 more date columns in gannt , some minor changes I have done in js and the dates are coming fine but when I try to updates the dates via calendar it roll back to previous dates 

Can u tell me the steps to add extra date columns in Gannt Chart

**Comment by robicch** [comment]
There are several steps.
Consider that start-end dates have a heavy impact on gantt logic.
How this two new dates impacts on start and end dates?
If you copied from the existing ones, you have to remove the logic for date propagation.
Hoping this helps,
Cheers,
Roberto

**Comment by Tanmaydeveloper** [comment]
How we will remove the logic of date propagation only for the two new date columns

**Comment by robicch** [comment]
Coding....

**Comment by Tanmaydeveloper** [comment]
Hi,
I am not able to get the place where and what should I code
  <td class="gdfCell"><input type="text" name="BaseLineStartDate" value="(#=obj.BaseLineStartDate#)" class="date"></td>
    <td class="gdfCell"><input type="text" name="BaseLineEndDate" value="(#=obj.BaseLineEndDate#)" class="date"></td>
    <td class="gdfCell"><input type="text" name="start" value="" class="date"></td>
    <td class="gdfCell"><input type="text" name="end" value="" class="date"></td>

We have the 4 rows in our gannt 
 the start and end dates works fine 
but BaseLineStartDate and BaseLineEndDate I am not able to modify it by calendar as it gets rollback

I need your help

**Comment by robicch** [comment]
If you want you can "hire" me for such task.
Please contact me directly: rbicchierai at open-lab dot com

**Comment by Edisson** [comment]
recently I added two more date-fields in this gantt-component, right it was rolling back after editing, but it's easy to fix in js events

**Comment by Tanmaydeveloper** [comment]
Hi Please tell me the code
Thanks in advance

**Comment by Edisson** [comment]
If I remember correctly it should be in el.blur(function (date) {} in the ganttGridEditor.js file.. I can send you the whole file on email and you compare it with original. Just give me your contact.

**Comment by Tanmaydeveloper** [comment]
Hi

Please send me the code on tanmay.a.srivastava@accenture.com

**Comment by Edisson** [comment]
I've sent from my gmail account

**Comment by Tanmaydeveloper** [comment]
Hi 
I haven't got it can u please resend or you may also resend on tanmaydeveloper@gmail.com

**Comment by Edisson** [comment]
let me know have you received the email

**Comment by SkyKOG** [comment]
@Edisson Hi could you also send me the aforementioned `ganttGridEditor.js` file with your `el.blur` overrides? I am also facing the same issue of the rollback happening when i change start dates.
my mail is akashdevaraju@gmail.com

Thanks in advance.
Best
-Akash
