### ISSUE TITLE
Increasing rendering speed

### ISSUE THREAD

**Issue by sirpresage** [robicch/jQueryGantt#35]
Hi, i need an information, i found out that twgantt was getting slower with a large set of events/gantt in one project which is normal. With 100 events, i recorded that the function loadproject was taking 2.8s.

So i searched a bit the reason and i have been able to reduce the execution to 1.7s. What i did is simply comment one line in ganttMaster.js, function loadproject.
//[expand]
//this.gantt.refreshGantt();
(line 390 in my custom version of twgantt)

I did a few test and haven't been able to see a difference in functionnality of twgantt.
Since the expand functionnality is somewhat new, i'm just asking this: is the line i commented really doing something, it seems refreshing is done even without it.

Thanks btw, twgantt is pretty cool, feel free to tell me if i should'nt ask this here, i'm discovering github ;)

**Comment by robicch** [comment]
Hi,
thank you for pointing out this issue.
Yes, you can comment that line.
Actually the refreshGantt() function is called in endTransaction

**Comment by robicch** [comment]
Changes committed.
