### ISSUE TITLE
Change disabled-date-status back when dependence is deleted

### ISSUE THREAD

**Issue by Edisson** [robicch/jQueryGantt#36]
Hi!
I'm not sure if it's "bug" when we delete a dependence between tasks, then the date doesn't change to enabled state

![dependence_1](https://cloud.githubusercontent.com/assets/3021151/6479866/f64633b0-c26d-11e4-9859-2ae4160af7a0.png)

![dependence_2](https://cloud.githubusercontent.com/assets/3021151/6479873/1d63c0d4-c26e-11e4-9351-582d8e8d7994.png)

please tell me is it normal behaviour?

**Comment by robicch** [comment]
Yes, it is.
Maybe in some cases it would be nice to "open" the dependent task, but I don't know how to choose the right case.

Any Idea?

**Comment by Edisson** [comment]
do you mean the right case it's a condition/event when we clearly see that dependency is removed?

**Comment by robicch** [comment]
I mean it is not a bug.
When you create a dependency, the depend task must "suspended" until the first one is "done", so It is easy to set the state when creating.

When you remove the dependency, I cannot know the previous state of the task, so I have no idea on the state that have to be restored.

**Comment by Edisson** [comment]
Yeh now I see but it might be better to leave it for user's responsibility?
