### ISSUE TITLE
removeClass 

### ISSUE THREAD

**Issue by doczoidberg** [robicch/jQueryGantt#39]
I am getting the error in removeClass function of svgdom:
Uncaught TypeError: Cannot use 'in' operator to search for 'marginTop' in undefined

any ideas?

**Comment by robicch** [comment]
Probably.  What version of jQuery are you using?
With latest versions, they optimized the way to search elements using some selectors. Unfortunately the implementation on SVG elements is not completely supported. You can change the selector.
I have already fixed this issue, but I'll release it after June

**Comment by doczoidberg** [comment]
problem was that my editor (visual studio) added breaklines to the comments `<!-- -->` .
