### ISSUE TITLE
Scroll position when scale Gantt diagram

### ISSUE THREAD

**Issue by Edisson** [robicch/jQueryGantt#40]
Hi Roberto! 
it's not an issue actually:) smth like an offer to change with snippet of code
I just wanted to add that (my) users claimed that it's not convenient to scale diagram when a project is very lingering in time.

when refresh gantt in js, the scroll position save and recover not correctly so I changed the code a bit   and seems it's more comfortable to work that way: 
https://gist.github.com/Edisson/8d5bf192eba0fd11225d

what do you think, Roberto? is it reasonably?

***
moreover I remove centering on today because it's move after saving the project - also not convenient when project is long, need to scroll back every time if we edit or watch smth.

**Comment by robicch** [comment]
I didn't see any difference in behavior (at least in my latest version).
Could you please give me more info on how to get the changes evident.

**Comment by Edisson** [comment]
ok, necessarily tomorrow at work I'll check it again and will try to show the difference

**Comment by Edisson** [comment]
I checked (cloned the last version), 
it works differently (for kind of a long proj) but you might say that it's not so good
I've done a few screenshots to see a behaviour of scroll position in you variant:
![3_2](https://cloud.githubusercontent.com/assets/3021151/7279676/1ed1cfc0-e937-11e4-92ce-0c259d47890a.jpg)
then zoom in:
![3_3](https://cloud.githubusercontent.com/assets/3021151/7279680/23f9c6c4-e937-11e4-8a46-7f6775843e86.jpg)
zoom in:
![3_4](https://cloud.githubusercontent.com/assets/3021151/7279681/278b71f2-e937-11e4-82c2-c8e8e1514b60.jpg)
zoom in:
![3_5](https://cloud.githubusercontent.com/assets/3021151/7279683/2a1f63ce-e937-11e4-99c4-3d2f7f858753.jpg)

mine:
![0_1](https://cloud.githubusercontent.com/assets/3021151/7279693/48e3c700-e937-11e4-85d5-24d895228ebe.jpg)
zoom in:
![0_2](https://cloud.githubusercontent.com/assets/3021151/7279695/4fe18330-e937-11e4-9318-d97031efdcc0.jpg)
zoom in:
![0_3](https://cloud.githubusercontent.com/assets/3021151/7279700/5892842a-e937-11e4-9e9b-38e46d34f000.jpg)
zoom in:
![0_4](https://cloud.githubusercontent.com/assets/3021151/7279701/5d49561a-e937-11e4-9279-767df8a98d4b.jpg)

or for instance I set scroll pos about in the middle, in my variant I got this zoom-behaviour then:
![1_1](https://cloud.githubusercontent.com/assets/3021151/7279722/8e85f472-e937-11e4-91e0-24efdc37e9b7.jpg)
![1_2](https://cloud.githubusercontent.com/assets/3021151/7279725/9301286e-e937-11e4-883a-39a5877aba24.jpg)
![1_3](https://cloud.githubusercontent.com/assets/3021151/7279729/975b786a-e937-11e4-8b8c-f635adf16205.jpg)
![1_4](https://cloud.githubusercontent.com/assets/3021151/7279732/9ac267d4-e937-11e4-9f31-9b2b5b6c8320.jpg)

so you see scroll keep its position (proportionally).
for our users it seems reasonable
however with your code it works another way. (it moves far to another months)

I just think if this little change is convenient for our users it will be good for many others:)

**Comment by robicch** [comment]
Ok, I I was testing the new version :-)
zooming:
![image](https://cloud.githubusercontent.com/assets/1381751/7293232/234017bc-e9a3-11e4-9d09-70c34af6a163.png)
![image](https://cloud.githubusercontent.com/assets/1381751/7293246/4d1d24d0-e9a3-11e4-909a-06e98b0a652b.png)
![image](https://cloud.githubusercontent.com/assets/1381751/7293249/59994dd8-e9a3-11e4-81ba-20952ae496d4.png)

now the center of the gantt side is kept on the center during the zoom.

I Hope to release the new version on June

**Comment by Edisson** [comment]
ah ok, that's great you have fixed it and going to release in the closest bright future:)
