### ISSUE TITLE
Time-scheduling

### ISSUE THREAD

**Issue by Edisson** [robicch/jQueryGantt#41]
Hi Roberto!

Just wanna ask and interest for a future.. 
your diagram is drawing good proportionally in scale of days and other ranges.

The question is: 
have you in plans to implement more detailed scale when we can see time-score while a whole day/night?:)

I know there are might be some disadvantages, such as draw performance and so on but what do you think?

**Comment by robicch** [comment]
Yes and no :-)
Yes: I already have developed for a customer a minute-resolution gantt editor.

No: i do not include such feature in the default trunk as the "master" gantt, the one included in Twproject Project management software, want to avoid micro-management, so the minimum scale for a project is one day.

If you are interested on thi feature, please write me rbicchieraiATopenUNDERSCORElabDOTcom

**Comment by Edisson** [comment]
thanks if we need it in the future I will write:)
