### ISSUE TITLE
Calendar month shift

### ISSUE THREAD

**Issue by Edisson** [robicch/jQueryGantt#42]
I've noticed one thing but didn't see yet how it works inside.

for example firstly select about the last day of a month
![calendar_1](https://cloud.githubusercontent.com/assets/3021151/7347022/bde6e6da-ecfd-11e4-82e3-783622a34ba9.png)
then make focus anywhere else and click again on that date-item month 
the caption of month is changed but we see the same calendar (days) for the previous month:
![calendar_2](https://cloud.githubusercontent.com/assets/3021151/7347023/bde969fa-ecfd-11e4-88cd-cc2871d04aec.png)

seems to me in this case we have a mismatch of caption of calendar and real days.
is it kind of a bug or a feature?

**Comment by robicch** [comment]
June 31th is a non-working day, so the start shifts to the next working day.

Is Sunday is working, set it on iI8nJs.js
