### ISSUE TITLE
Printing gantt-diagram

### ISSUE THREAD

**Issue by Edisson** [robicch/jQueryGantt#43]
Hi again!:)
Now I'm interested in printing out diagram.. but it looks another way, not like people wanna see it on a paper:
![printgantt1](https://cloud.githubusercontent.com/assets/3021151/7488381/d3448b86-f3e2-11e4-8666-f73be6b71220.png)
![printgantt2](https://cloud.githubusercontent.com/assets/3021151/7488380/d3444d06-f3e2-11e4-96cd-5b384fb6b21a.png)

we have two different lists. 

is it possible to print the diagram (both of two splitBoxes) in one list like we see it in browser window (side by side, quite the contrary)?

and then, for instance, to prolong the second splitBox with graphic into the other lists?

**Comment by robicch** [comment]
This is done in order to have the maximum space available. Rows are of the same size so that you can stitch the two sheets  together.

If yo want to change the behavior, have a look to ganttPrint.css stylesheet, in particular to .splitBox2 class (page-break-before)

**Comment by Edisson** [comment]
ок, got it, thanks!:)

**Comment by Edisson** [comment]
Roberto and what about printing the whole available area of the splitbox2? 

I mean if there is a long project exists, we can print out only the start of project visible part. 
scaling doesn't fit because there could be very long term in use.
how it's possible to prolong printing-area through the whole length of splitbox2 to other printing-pages in scale that I really need in a moment.

**Comment by robicch** [comment]
We are working on this matter too, but HTML support for printing is very poor

**Comment by Edisson** [comment]
Yeh recently I figured it out:)
So when your admirers can see the new version of this printing feature? Also approx in the middle of the summer?

**Comment by robicch** [comment]
The new Twproject version is almost ready, but in order to clean the Gantt component from Twproject dependencies will require some additional work.
Yes, end of this summer is a reasonable milestone :-)

**Comment by NamanSuri** [comment]
Hi Robicch,

Has the issue of printing all the Gantt (.splibox2) items for  long projects i.e. having more than 300 task been resolved.

As we are facing issues and we are able to print all the 300 tasks but the Gantt is only printing itens visible on the screen.

Thanks in advance.

Naman
