### ISSUE TITLE
Moving table header

### ISSUE THREAD

**Issue by Edisson** [robicch/jQueryGantt#46]
Someday we had loaded a lot of records (2 thousands) in Gantt and started to scroll down/up. Sometimes the header of table in the first splitter goes away (up and down). 
In light of the fact that we change a lot in this component I thought likely it's my fault and carried out an experiment by loading experimental data in the original Gantt diagram. So here is the same symptom on screens:
![ganttheader2](https://cloud.githubusercontent.com/assets/3021151/8279483/7fc211f0-18ee-11e5-9dd3-9aff597b330d.png)
![ganttheader](https://cloud.githubusercontent.com/assets/3021151/8279486/8238bde4-18ee-11e5-8e1e-9c20969531f2.png)

Can't understand dependencies and conditions when it happens, how we could fix it?

**Comment by Edisson** [comment]
I've done a little change in ganttUtilites.js file,
Removed a line of code in a sync scrolling function:

```javascript
    fs.scroll(function(e) {
        // code here...
      if (el.is(".splitBox1") && stopScroll!="splitBox2"){
        // code here...
      }else if (el.is(".splitBox2") && stopScroll!="splitBox1"){
        // code here...
      }
        // code here...
      //This code I removed: where.stopTime("reset").oneTime(100,"reset",function(){stopScroll="";})
    });
```

it seems to me that kind of those behaviour is disappeared, but I'm not sure if it's a really decision in this case?

**Comment by Edisson** [comment]
don't wanna put a new issue, just have a question about performance of gantt drawing. 
how we can increase it? when there is a lengthy range of calendar grid and a lot of records it's making up slowly

**Comment by robicch** [comment]
See the issue #35.
Consider that this component is meant to run with max 100 tasks.
There is a Profiler object already in the component you can use to inspect the performances.
I had a look in the beginning, and I sow that there was not a bottleneck, but the time was spread on several functions. 
I have no idea on how to improve the speed. 
Any suggestion will be welcome :-)

**Comment by Edisson** [comment]
for example in some diff places we can replace ".is()" to ".hasClass()" - it works faster:) but it's not regarding of drawing Gantt in common.. but if I find a decision I will tell.

about the header: there is out of sync in scrolling sometimes and it's floating.

**Comment by Edisson** [comment]
what I've noticed is that scrolling with moving header works not really good (floating) in IE11.. the header of grid is like blinking and seems it has smth in common with that bug I had described in the first message with screenshots

**Comment by Edisson** [comment]
we also can change the snipet of code in scroll:
```javascript
      secondBox.find(".fixHead").css('top', top);
      firstBox.find(".fixHead").css('top', top);
```
to 
```javascript
      $('.fixHead').css('top', top);
```
it works faster but it doesn't help to avoid header floating in IE.
