### ISSUE TITLE
Add new column with select box

### ISSUE THREAD

**Issue by anitabharambe** [robicch/jQueryGantt#48]
Hi,

I am trying to add a new column in gantt. The new column is accepting the value from the select box. I am able to show that new column and able to select any value from drop down, but while saving the gantt that particular column and value is not passed in json.
If I try a new text column the it works perfectly.

Can you help to solve my issue.

Thanks,
Anita

**Comment by Edisson** [comment]
I had the same problem a long time ago
as far as I remember there are several points in js-modules where you have to change/add new field that you wanna have in diagram. 
If it's not passed in json, likely you haven't changed code where the save procedure executes

**Comment by robicch** [comment]
Right!
