### ISSUE TITLE
Change calendar and createBlackPage to bootstrap datepicker and bootstrap modal

### ISSUE THREAD

**Issue by psnma** [robicch/jQueryGantt#51]
It would be a good idea to use modal bootstrap and bootstrap datepicker.

**Comment by Edisson** [comment]
Totally agree. In particular we replaced the datepicker to another one in our own project

**Comment by psnma** [comment]
You are using bootstrap modal? I tried use replacing createblackpopup, but seems to stay in memory, , even when you edit a 'row', edited previously are changed together.

**Comment by Edisson** [comment]
in the main project where our Gantt is currently we use jqWidgets. But in other new projects sometimes we use bootstrap. And we think to change jqWidgets to smth else
