### ISSUE TITLE
Focus lost on editor when task are minimised

### ISSUE THREAD

**Issue by varuns1305** [robicch/jQueryGantt#52]
Hi, i have been using your library for the past 6 months and it works amazingly well. But, there is one issue that i have come across recently wherein when the tasks are minimized, the focus on the the gantt editor is lost and the down and the up arrow keys behave a liitle wierd . Have attached a screenshot for the same.

![gantt focus issue](https://cloud.githubusercontent.com/assets/13101147/9655662/6dbd2ea4-5250-11e5-9621-9e5310ad3ec4.png)

**Comment by robicch** [comment]
Solved on the latest version
