### ISSUE TITLE
feature-request: allow to specify duration as a date-range instead of working days

### ISSUE THREAD

**Issue by JoernT** [robicch/jQueryGantt#55]
if using an external data provider it's hard to calculate the working days. Instead it would be great if one could specify a duration between two dates. Would be fine enough if weekends are just ignored to calculate the actual working days.

**Comment by robicch** [comment]
Actually the TaskFactory.build function uses only "start" and "duration" in days.
Then regarding working days, just change the isHoliday function implementation on i18nJs.js file.

Hoping this helps.
Roberto

**Comment by JoernT** [comment]
Thanks for quick reply - at least that gives me the pointers i was looking for. Thanks
