### ISSUE TITLE
Task2 starting with next consecutive date of Task1's end date, If it depends on Task1

### ISSUE THREAD

**Issue by satishdvnk** [robicch/jQueryGantt#66]
Let us consider, I have two tasks with start date and end dates and Task2 depends on Task1.
Once chart is loaded, currently after showing the Task1, the Task2 start date is being considered as the next consecutive date of Task1 end date (Even if Task2 has different start date).

**Comment by robicch** [comment]
Yes, of course.
Depending task must begin the day after the "master" close. Eventually you can set a lag
using "dep:lag" syntax.
