### ISSUE TITLE
Error while loading saved resources in a task

### ISSUE THREAD

**Issue by anoopantony8** [robicch/jQueryGantt#70]
Hi,
I am facing an issue while loading the saved resources for tasks.The resources added are shown in the listing of all tasks,but when i try the edit of a task,there is no resource selected there and the console shows an error "jquery.JST.js:99 JST error: ASSIGNMENT_ROW obj.assig.id.indexOf is not a function".Please reply back it's urgent

**Comment by robicch** [comment]
Probably task assignment data are corrupted, incomplete or invalid. Check that resources id matches with the one reported on assignment.

**Comment by anoopantony8** [comment]
Hi Rob,
Thanks for the reply, actually i checked resources id and assignment id they both match.Is my task assignment data is in correct format or not?The following is my task assignment data
"assigs": [{"name": "AnoopAntony", "resourceId": 1, "id": 1, "roleId": "", "effort": 0}]

**Comment by nakul-sayone** [comment]
@robicch
 Hi, i am also facing the same issue.
Can you  please explain  to me how to   solve this .
Just like @anoopantony8 said I’m also sending same JSON array .
Please reply soon .
Its kinda urgent

**Comment by angeloocana** [comment]
Did you tried Ids as strings?
Could you create a plunker example? it will help everybody.

**Comment by nakul-sayone** [comment]
@angeloocana Thanks. that was the issue. @angeloocana  you are a life saver .
