### ISSUE TITLE
Error: localStorage.getObject is not a function

### ISSUE THREAD

**Issue by angeloocana** [robicch/jQueryGantt#71]
Hi,

thanks for this repo!!!

I'm using jquery 1.12.1, and i got this error: localStorage.getObject is not a function
I changed to : localStorage.getItem
and works fine!

**Comment by robicch** [comment]
getObject is never used on jQueryGantt.
Where did you find it?

**Comment by oliiix** [comment]
it's used in ganttUtilities.js on line 172, at least most recent version and i get the same error... trying to bind it into laravel 6

**Comment by sftl** [comment]
> it's used in ganttUtilities.js on line 172, at least most recent version and i get the same error... trying to bind it into laravel 6

I also have this issue. `localStorage.getObject` is used in `loadGridState` function in gantUtilities.js file.
By the way, there is also a `localStorage.setObject` on line 165

Cheers
Thank you

**Comment by sftl** [comment]
> > it's used in ganttUtilities.js on line 172, at least most recent version and i get the same error... trying to bind it into laravel 6
> 
> I also have this issue. `localStorage.getObject` is used in `loadGridState` function in gantUtilities.js file.
> By the way, there is also a `localStorage.setObject` on line 165
> 
> Cheers
> Thank you

Ok, found the solution. Just load `libs/utilities.js`

Sorry.
Thank you for this great tool
