### ISSUE TITLE
No template for TASKROW (error when enabled)

### ISSUE THREAD

**Issue by KingGeneral** [robicch/jQueryGantt#72]
Dear @robicch , 

i have a problem when enable template " 'TASKROW' " 
(master branch) (latest version)

No template found for type 'TASKROW'
location in the view : 
`<div class="__template__" type="TASKROW"> <!-- ... --></div>`

regards,
KinGen

![error when template taskrow enable](https://cloud.githubusercontent.com/assets/9468485/18781238/2572d7e4-81ab-11e6-8a0f-43b4838cc1c5.jpg)

**Comment by KingGeneral** [comment]
@angeloocana did you get the error from this one too ?

**Comment by robicch** [comment]
No. Its work correctly.
Be careful: templates are defined inside html comments, and sometime editors remove them

**Comment by KingGeneral** [comment]
thx @robicch , i recheck it this day, and what trigger that error is : 
this line 

`(#=obj.hasExternalDep?"readonly":""#)`

(and Note to other that like me : if you are using the template, it must be free of `<!-- -->` or it will not run )

btw thx for the fast response @robicch
