### ISSUE TITLE
Make Date follow your millis (solution)

### ISSUE THREAD

**Issue by KingGeneral** [robicch/jQueryGantt#73]
Dear @robicch , 
here i made a few fix to the code of yours, **(see the preview at attachment img)**
so that user can make their `1396994400000`
to the exact time : `Wed Apr 09 2014 05:00:00 GMT+0700`

first see your `gantt.html`
then edit `function loadFromLocalStorage()` code , here : 

```
function loadFromLocalStorage() {
  var ret;

...  

    //actualiza data
    //var offset=new Date().getTime()-ret.tasks[0].start;   //original Master Code , just comment it.
    var offset=ret.tasks[0].start/100000;     //Do / add this line code this one to make it independent
    console.log(offset);
    for (var i=0;i<ret.tasks.length;i++)
      ret.tasks[i].start=ret.tasks[i].start+offset;
  }
  ge.loadProject(ret);
  ge.checkpoint(); //empty the undo stack
}
```

thx, @robicch for your TWproject  
hope you like it :D 

Regards,
#KG

![fixing the millis realtime time](https://cloud.githubusercontent.com/assets/9468485/18941073/09458ce2-8638-11e6-838e-9e4b94502e3c.png)

**Comment by robicch** [comment]
Hi @KingGeneral,

the "actualize data" piece of code is useless in a real environment and you can remove it completely.
It has been developed just to "shift" the example project to today.
Moreover the hours of start and end dates are always set to the first millis and last millis of the day respectively.

**Comment by KingGeneral** [comment]
omg, thats simple... hope I get better luck next time... thx @robicch , 
that date haunt me as newbie 4sure :D
