### ISSUE TITLE
Root / Parent end date not following latest task date

### ISSUE THREAD

**Issue by KingGeneral** [robicch/jQueryGantt#74]
Dear @robicch ,

I have a big issue,
Root / Parent end date not following latest task date
example at root => its mean the range of the project itself, (from starting to end)

when i try i just find self.master.changeTaskDates(task, task.start, task.end);
any info about this ?

![screenshot_9](https://cloud.githubusercontent.com/assets/9468485/19711029/f0fd4c1c-9b5c-11e6-9624-0657c5c58a1d.jpg)

**Comment by robicch** [comment]
Hi @KingGeneral ,

this is not an issue, this is by design.
On Twproject (the Project Management Solution this editor comes from), parents task can be wider than children, so that you can set "spare days", just in case.

**Comment by KingGeneral** [comment]
do you have any trick to make them following the tail of last task ??? (at least the root so it will be usefull, or not it will be a waste (level 0) )

#help
