### ISSUE TITLE
October 15, 2016 is duplicated

### ISSUE THREAD

**Issue by psnma** [robicch/jQueryGantt#75]
October 15, 2016 is duplicated, and tasks are in trouble in alignment.

**Comment by KingGeneral** [comment]
what you mean by duplicated ??? 

![image](https://cloud.githubusercontent.com/assets/9468485/19751119/376f0b58-9c21-11e6-81e5-8067b4458fe9.png)

**Comment by psnma** [comment]
Look in https://gantt.twproject.com/applications/gantt/distrib/gantt.jsp
![captura de tela 2016-10-26 as 23 56 59](https://cloud.githubusercontent.com/assets/808500/19751950/130d3210-9bd8-11e6-9fb3-3a6366624bd5.png)

**Comment by KingGeneral** [comment]
i already look at it , but it still there at fixed number

![image](https://cloud.githubusercontent.com/assets/9468485/19752046/6d5b37fc-9c24-11e6-8f02-d7c90df45cfd.png)

**Comment by KingGeneral** [comment]
i already look at it but its still there at fixed number, idk but nothing wrong.

![image](https://cloud.githubusercontent.com/assets/9468485/19752069/a590774a-9c24-11e6-8c8c-624cb6ab18e5.png)

**Comment by robicch** [comment]
This should be solved with the latest version
