### ISSUE TITLE
hanging application while updating dates(issue fixed) but zoom view i need to set at Quater level

### ISSUE THREAD

**Issue by shakti26** [robicch/jQueryGantt#78]
I have more than 100 record , but when i am modifying startdate /enddate /duration. it’s taking too much time to update its all parent dates (from last parent to first  top level parent).
I have been modified Gantt chart very much like, **I added two dropdown to select assign user to each task,
Progress and Budget column of each task.**
but only when modifying dates, it’s taking too much time.

**is it possible that when i try to modify dates it should modify only text on the gantt editor.**
![gantt 2](https://cloud.githubusercontent.com/assets/26320392/23785831/a0fd35ae-058f-11e7-941f-8841893aee06.PNG)

**Comment by shakti26** [comment]
**Must Read...** Last issue solved
_One thing i noticed, while updating a record in gantt chart and the level of Zoom is 3 or 'Q view' then i am able to update record very very fast even if we have more than 100 record.
but if it is either Month View or Week View or Day View It is taking minimum 3 second to update a row.
what can we Do ?_

**Comment by cbeckner12** [comment]
Hi shakti26 - I was wondering, I noticed that your image has an updated CSS for this awesome project, do you mind sharing?

**Comment by shakti26** [comment]
ya sure as soon as possible i would like to share.

Regards,
Shakti Kumar
+91 9700983867
Software Developer
Infionic India Pvt Ltd., Hyderabad
