### ISSUE TITLE
Templates and createModalPopup

### ISSUE THREAD

**Issue by nelsongnza** [robicch/jQueryGantt#84]
Congratulations, for excelent and great work !!! I hope don't bothers you, Please show me information about how to use templates and then createModalPopup for capture input value; I was playing with, templates create pretty good and then append to ModalPopup by createModalPopup, but Decorate does't make the click event and I can't use input type hide where put intereted value...

$.JST.loadDecorator("SELECT_PROJ", function(myselTr, myselres){
    myselTr.find("#projectList>ul>li").click(function(){
		var mid=$(this).id;
		alert("list selected id "+$(this).id);
		$("#selectedpry").val(id);
	});
	}); 
Again very good work, thanks for your attention...

cheers !

**Comment by robicch** [comment]
Hi,
 the problem is that

> var mid=$(this).id;  

responds "undefined" always,
you should use 
var mid=$(this).prop("id");

**Comment by nelsongnza** [comment]
Mr. Roberto,
Really thanks for your answer,

Decorator never work fine with me, i don't know why...
I solved it with this solution:

1.- Create Template:
<div class="__template__" type="SELECT_PROJ"></div>

2.- Event onclick=myProjects() and into function create template and call ajax for read from server project list available:
  function myProjects(){
	var idUsuario=<?php echo ($idUsuario)?$idUsuario:'1';?>;

	var selector=resourceSelectProj = $.JST.createFromTemplate({}, "SELECT_PROJ");
	resourceSelectProj.find("#iduserin").val(idUsuario);

	$.ajax({
		url: 'selectProjListFromServer.php',
		type: 'POST',
		dataType: 'html',
		data: {idUser:idUsuario,statusd:statusv},
		})
		.done(function(e) {
			console.log("success OnMisProyectoServer...");
			$('#projectList').html(e);
		})
		.fail(function() {
			console.log("error OnMisProyectoServer...");
			alert("Error de Ajax OnMisProyectoServer...");
		})
		.always(function() {
			console.log("completando OnMisProyectoServer...");
		});
	
	var ret=createModalPopup('60%','50%','','','');
	ret.append(resourceSelectProj);
	
  return;
  }
3.- Load values into hidden inputs through onclick=asignarid(this) event on list projects availables from server and showed in model popup, and show button Cargar:
  function asignarid(a){
		var id=a.id;
		var statusd=a.className;
		$("#projectList>ul>li").css({"background-color":"#91B4B7"});
		$("#projectList>ul>li[id="+id+"]").css({"background-color":"#34495e"});
		$("#cargarButton").css({"display":"block","position":"relative","align":"center"});
		$('#selectedpry').val(id);
		$('#statusimp').val(statusd);
		return;
  }
4.- Then fianally with onclick=verngm() on load Button:
  function verngm(){
	var idprj = $('#selectedpry').val();
	var ostats = $('#statusimp').val();
	loadGanttFromServer(idprj, ostats);
	closeBlackPopup('');
	$("#projectClientSel").val(idprj);
  return;
  }

Mr. Roberto,
I repeat my thanks You,

Another hands:

Resource Editor Decorator again doesn't work,
I solved it with:

1.- Don't use decorator click function, instead into resourceEditor() function add:
  resourceEditor.find(".delRes").click(function(){
	  $(this).**closest("tr")**.hide(500,function(){
		  $(this).closest("tr").remove();
	  });
});

look at your version there is **closest("td")** and then suddendly close modal popup and row (resource) it is not deleted from resourses table...

Do you have some information for read, how to, or somethings like that, for I read it and finally, I can may be understand for take inputs information from modal popup after ajax give information from server...

I hope don't bother you, Thanks for your attention...
