### ISSUE TITLE
Dates of the mother activities with the dates of the children activities

### ISSUE THREAD

**Issue by Ftes80** [robicch/jQueryGantt#85]
Hello congratulation by your great job,we are been working in your project and According to our methodology that we follow said that the dates of the mother activities should be governed in its start date by its smallest start date of its children activities and in the case of the end date of the mother activities should be governed by its bigger  end date of its children activities
Part of this process is working correctly but the problem is that when you move an children activity to the right, the mother activities still with the same date, when shoud also move with the same dates that the children activities.
we tried to fix according with our methodology but we cant so we think that the problem its in the file ganttTask.js in the function updateTree .

Sorry by my mistakes in my writting , my english si not perfect.

**Comment by robicch** [comment]
On our model parent activity is not a simple "group" of simpler activities, but has its own assignment and dates that can be larger that the max of its children.
