### ISSUE TITLE
datepicker does not keep in place (stick to the input control) while scrolling?

### ISSUE THREAD

**Issue by itszerocode** [robicch/jQueryGantt#86]
Datepicker appears in right place on cell which is my start date or end date field. 
But when I scroll the page down the datepicker scrolls down along with the page. 
I want it to stick to the input field. 
Any help/ quick fix would be appreciate.
Thanks

**Comment by itszerocode** [comment]
Fixed in Css

**Comment by robicch** [comment]
how?
