### ISSUE TITLE
The header jumps anywhere on the page while scrolling.

### ISSUE THREAD

**Issue by itszerocode** [robicch/jQueryGantt#87]
When I scroll the page up/down faster then the header moves anywhere in the page.
e.g. center of the grid control or bottom etc.
 I am loading more than 100 task on the page with lot of other custom columns such as 
Status, Last Edited, Comments, etc. 
I have implemented filters on the data, and every time when user applies filter I call 
laodTask() from the GanttMaster.js method with new set of tasks.
after this event, I observed that the header position gets disturbed while scrolling the page.

**Comment by robicch** [comment]
fixed
