### ISSUE TITLE
How can I set weekend day  as workday  ?

### ISSUE THREAD

**Issue by JimmyPoor** [robicch/jQueryGantt#88]
plz for help , I try to change source code but met some issue

**Comment by robicch** [comment]
please describe the issue in detail

**Comment by JimmyPoor** [comment]
ok, when I change method named "isHoliday" in config js file and return false means without using any holidays,but when I save all tasks in list the date will changed automatically, strange that if I use weekend day as holiday this issue will not happen

**Comment by robicch** [comment]
Task start and end dates must match with duration that is computed in working days. 
If you changed the working days computation, the dates will change accordingly when the project is loaded.

**Comment by JimmyPoor** [comment]
thanks robicch for reply!  you mean if I implement duration modification  for working days (include Sat and Sun) in this method ? For example ,current workdays  are whole week and where I change logic in (like days%7?)
