### ISSUE TITLE
Header issue in Edge/IE

### ISSUE THREAD

**Issue by mihirkadam** [robicch/jQueryGantt#91]
There is some lag while scrolling.
Environment details (Windows)
![image](https://user-images.githubusercontent.com/10244487/28161393-01fc6fec-67e1-11e7-9e7d-90ecda82a1d6.png)

Please find screep capture 
![ganttchart](https://user-images.githubusercontent.com/10244487/28161360-e33c7ffc-67e0-11e7-8e41-2aeed45ab9c4.gif)

**Comment by robicch** [comment]
fixed

**Comment by mihirkadam** [comment]
Really appreciated :) :)
