### ISSUE TITLE
When user scrolls vertically till the end of the container the left side header position in miscalculated

### ISSUE THREAD

**Issue by itszerocode** [robicch/jQueryGantt#94]
When user scrolls vertically till the end of the container the left side header position in miscalculated
![headerspaceforgit](https://user-images.githubusercontent.com/1611906/28819593-584af57c-76cc-11e7-835c-a5ade2ba084f.PNG)

**Comment by eduardobelchior** [comment]
Did you solve this problem?

**Comment by mihirkadam** [comment]
Just add below CSS line 

.ganttSVGBox{
  overflow-y: hidden; /*IE11 bug*/
}
