### ISSUE TITLE
logic to add 12 hours in start date 

### ISSUE THREAD

**Issue by mihirkadam** [robicch/jQueryGantt#97]
I just want to know the logic behind this.

![dates](https://user-images.githubusercontent.com/10244487/28966599-bed029b0-7934-11e7-9865-61f9fdc50e52.png)

**Comment by robicch** [comment]
it is a sort of insurance for the daylight saving, milliseconds missing and so on :-)

**Comment by mihirkadam** [comment]
thank you :) :)

**Comment by mihirkadam** [comment]
you can close this issue. :) :)
