### ISSUE TITLE
insert above/ insert below cause  circular reference

### ISSUE THREAD

**Issue by wswind** [robicch/jQueryGantt#98]
tasks like this:

1
2
3 depend 2
4 depend 3

select row 3 insert and cancel 
tasks become like this:
1
2
3 depend 2
4 depend 4

press save then refresh

this may cause circular reference

**Comment by wswind** [comment]
i have fixed it and made a pull request

**Comment by wswind** [comment]
this may cause circular reference

**Comment by wswind** [comment]
1     
2   
3   depend 2
4   depend 3


select row 3 insert and cancel 
1     
2   
3   depend 2
4   depend 4

this may cause circular reference

**Comment by robicch** [comment]
Fixed on just released version
