### ISSUE TITLE
Can we use jQueryGantt library for commercial use? 

### ISSUE THREAD

**Issue by mihirkadam** [robicch/jQueryGantt#99]
We want to make a modification to this library and create a new product. Is there any licensing restriction?

**Comment by robicch** [comment]
It is MIT licensed, so just keep the attributionof theorigina authors.
No fees.
Cheers,
Roberto


Il giorno gio 10 ago 2017 alle 21:45 Mihir Maruti Kadam <
notifications@github.com> ha scritto:

**Comment by mihirkadam** [comment]
As per my understanding, we just have to maintain below lines in JS. 
![image](https://user-images.githubusercontent.com/10244487/29249734-f1fd0676-8052-11e7-95cd-4aeb405a1bee.png)

Thank you, @robicch . I appreciate your efforts and all the contributors of this library :) :)

**Comment by robicch** [comment]
Yes, exactly
